### ISSUE TITLE
400 error on download

### ISSUE THREAD

**Issue by dweagle79** [s0len/meta-manager-config#20]
Not sure what this means. It's the only error I get from your overlays.

Overlay Error: Status 400 when attempting download of: https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/network-top-left/#0.png |

**Comment by ymendel** [comment]
You need to use https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/network-top-left/%230.png

The `#` is a special character.

If you're getting `#0` as a variable in PMM and not some hard-coded text, then use the `_encoded` version of the variable. (see https://metamanager.wiki/en/latest/files/templates/?h=_encoded#template-definition)

**Comment by shanester64** [comment]
Same results here. The script runs, with the network overlays and status with exception...
Here are the last errors of the log..

Plex Error: network: Crave not found
Overlay Error: Status 400 when attempting download of: https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/network-top-left/#0.png 

Using the code from the exampleconfig (replacing pmm with default, per kometa)
- default: network
      template_variables:
        horizontal_align: left
        horizontal_offset: 0
        vertical_offset: 0
        vertical_align: top
        back_width: 1000
        back_height: 1500
        url: https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/network-top-left/<<key>>.png 
        back_color: 00

**Comment by Droppisalt** [comment]
@dweagle79  @shanester64
Not sure for Shane's Crave error. But for the #0.png error, here's what I did (last line):
```
- default: network
  template_variables:
    horizontal_align: left
    horizontal_offset: 0
    vertical_offset: 0
    vertical_align: top
    back_width: 1000
    back_height: 1500
    url: https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/network-top-left/<<key>>.png
    url_#0: https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/network-top-left/%230.png
```
